resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/1.yaml
packages:
- .
extra-deps:
- stm-2.5.1.0
- network-3.1.4.0
- tasty-1.5
- tasty-hunit-0.10.0.3